### PR TITLE
Externalize config from Docker image

### PR DESCRIPTION
**Pull request by jycr**
fix: #30

This pull request includes significant changes to the Docker configuration and the way the application handles environment variables. The most important changes are the addition of a `.dockerignore` file, updates to the `Dockerfile`, and the creation of a new `config.ts` file that handles environment variables differently depending on whether the application is in production or development mode. The application's Vue components and API calls have also been updated to use this new configuration file.

### CODE REVIEW

**Review by karpikpl — APPROVED** [review]

**Comment by dcieslak19973** [comment]
Any ETA on approving this?

**Comment by dcieslak19973** [comment]
bump.... @karpikpl / @martedesco

**Comment by karpikpl** [comment]
@dcieslak19973  I merged this PR into mine #55 and resolved conflicts but I have no control when it will be merged by @DevOps-zhuang

**Comment by martedesco** [comment]
Thanks! I was in holidays for a while. I will review it and merge it this week 👍🏼

**Comment by karpikpl** [comment]
Just to be clear - this PR fixes the env. variables but token is still hardcoded and exposed. I would not recommend deploying this to AKS or any production-like environment.

#55 is trying to mitigate it by keeping the token server side (not in the browser)

**Review by martedesco — APPROVED** [review]

**Pull request merged**
